export const lightTheme = {
  "theme_color": "#2563EB",
  "main_background": "#FFFFFF",
  "comment_box_background": "#FFFFFF",
  "comment_box_border": "#E5E7EB",
  "comment_box_border_radius": "8px",
  "comment_box_shadow": "none",
  "primary_text_color": "#111827",
  "secondary_text_color": "#6B7280",
  "input_background": "#F9FAFB",
  "input_border": "#E5E7EB",
  "input_border_radius": "6px",
  "input_shadow": "none",
  "accent_color": "#2563EB",
  "accent_color_hover": "#1D4ED8",
  "accent_text_color": "#FFFFFF",
  "button_background": "#2563EB",
  "button_background_hover": "#1D4ED8",
  "button_text_color": "#FFFFFF",
  "button_border_radius": "6px",
  "header_background": "#F9FAFB",
  "header_text_color": "#111827",
  "reaction_button_background": "#F3F4F6",
  "reaction_button_border": "#E5E7EB",
  "reaction_button_hover": "#E5E7EB",
  "footer_background": "#F9FAFB",
}

export const darkTheme = {
  "theme_color": "#3B82F6",
  "main_background": "#111827",
  "comment_box_background": "#1F2937",
  "comment_box_border": "#374151",
  "comment_box_border_radius": "8px",
  "comment_box_shadow": "none",
  "primary_text_color": "#F9FAFB",
  "secondary_text_color": "#D1D5DB",
  "input_background": "#374151",
  "input_border": "#4B5563",
  "input_border_radius": "6px",
  "input_shadow": "none",
  "accent_color": "#3B82F6",
  "accent_color_hover": "#2563EB",
  "accent_text_color": "#FFFFFF",
  "button_background": "#3B82F6",
  "button_background_hover": "#2563EB",
  "button_text_color": "#FFFFFF",
  "button_border_radius": "6px",
  "header_background": "#1F2937",
  "header_text_color": "#F9FAFB",
  "reaction_button_background": "#374151",
  "reaction_button_border": "#4B5563",
  "reaction_button_hover": "#4B5563",
  "footer_background": "#1F2937",
} 